[tox]
min_version = 4.0
env_list = pep8, py3

[testenv]
extras = test
commands = pytest {posargs:pkg_resources/tests}

[testenv:pep8]
deps =
    ruff
commands =
    ruff check {posargs:.}
    ruff format --check {posargs:.}

[testenv:docs]
extras = doc
commands = sphinx-build -W -b html doc/source doc/build

[testenv:cover]
extras = test
deps =
    pytest-cov
commands =
    pytest --cov=pkg_resources --cov-report=html:cover --cov-report=xml:cover/coverage.xml {posargs:pkg_resources/tests}

[testenv:venv]
commands = {posargs}
